# Generated by Django 3.2.5 on 2021-07-30 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_link',
            field=models.CharField(default='', max_length=500),
        ),
    ]
